"""empty message

Revision ID: 0e15fd5b4c8e
Revises: 5161db6a57a6
Create Date: 2020-01-29 21:48:26.402140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e15fd5b4c8e'
down_revision = '5161db6a57a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AS_Category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AS_Category', schema=None) as batch_op:
        batch_op.drop_column('training')

    # ### end Alembic commands ###
