"""empty message

Revision ID: 8503f5440f2e
Revises: d45e1b68d890
Create Date: 2020-04-09 17:19:59.317030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8503f5440f2e'
down_revision = 'd45e1b68d890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Firefighter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_uid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Firefighter', schema=None) as batch_op:
        batch_op.drop_column('sync_uid')

    # ### end Alembic commands ###
