"""empty message

Revision ID: 96cb956dd977
Revises: 04be936180c7
Create Date: 2020-04-23 08:57:39.745598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cb956dd977'
down_revision = '04be936180c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lodur_general', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('value', sa.String(length=64), nullable=True))
        batch_op.drop_column('last_sync')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lodur_general', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync', sa.DATETIME(), nullable=True))
        batch_op.drop_column('value')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
