"""empty message

Revision ID: 988335d334a8
Revises: 0e15fd5b4c8e
Create Date: 2020-04-06 13:52:47.252958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988335d334a8'
down_revision = '0e15fd5b4c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alarm_GVZnotAvailable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isKader', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alarm_GVZnotAvailable', schema=None) as batch_op:
        batch_op.drop_column('isKader')

    # ### end Alembic commands ###
