"""empty message

Revision ID: d45e1b68d890
Revises: 988335d334a8
Create Date: 2020-04-07 21:24:54.406800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45e1b68d890'
down_revision = '988335d334a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Firefighter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eintritt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Firefighter', schema=None) as batch_op:
        batch_op.drop_column('eintritt')

    # ### end Alembic commands ###
